(() => {
  const API='https://wte-cloud-api.onrender.com';
  const $=id=>document.getElementById(id);
  const authToken=()=>localStorage.getItem('wte_cloud_token_v4')||sessionStorage.getItem('wte_session_token_v8')||localStorage.getItem('wte_cloud_token_v2')||'';
  async function request(path,options={}){const response=await fetch(API+path,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${authToken()}`,...(options.headers||{})}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Errore ${response.status}`);return data;}
  function openPractice(id){const card=[...document.querySelectorAll('[data-id]')].find(node=>String(node.dataset.id)===String(id));if(card){card.click();card.scrollIntoView({behavior:'smooth',block:'center'});return;}alert(`Apri la pratica ${id} dall’Archivio.`);}
  function setupBanner(automation){const missing=[];if(!automation.emailConfigured)missing.push('e-mail');if(!automation.whatsappConfigured)missing.push('WhatsApp');const root=$('workflowSetup');if(!missing.length){root.className='workflow-setup ready';root.textContent='Invii automatici configurati.';return;}root.className='workflow-setup warning';root.textContent=`Motore attivo. Da collegare il canale ${missing.join(' e ')} nelle variabili Render.`;}
  function renderExceptions(items){const root=$('workflowExceptionList');if(!items.length){root.innerHTML='<div class="workflow-empty">Nessuna azione richiesta.</div>';return;}root.innerHTML=items.map(item=>`<article class="workflow-item ${item.severity}"><div><strong>${item.title}</strong><span>${item.customer||item.practiceId||''}${item.eventDate?' · '+item.eventDate:''}</span><p>${item.description}</p></div><div class="workflow-item-actions">${item.practiceId?`<button data-open="${item.practiceId}">Apri</button>`:''}<button data-resolve="${item.id}">Risolto</button></div></article>`).join('');root.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>openPractice(button.dataset.open));root.querySelectorAll('[data-resolve]').forEach(button=>button.onclick=async()=>{try{await request(`/api/workflow-exceptions/${button.dataset.resolve}/resolve`,{method:'POST',body:'{}'});await load();}catch(error){alert(error.message)}});}
  function renderUpcoming(items){const root=$('workflowUpcomingList');if(!items.length){root.innerHTML='<div class="workflow-empty">Nessun evento futuro.</div>';return;}root.innerHTML=items.map(item=>`<button class="workflow-upcoming" data-open="${item.id}"><strong>${item.name||item.id}</strong><span>${item.date||''}${item.time?' · '+item.time:''}</span><small>${item.location||''}</small></button>`).join('');root.querySelectorAll('[data-open]').forEach(button=>button.onclick=()=>openPractice(button.dataset.open));}
  async function load(){if(!authToken())return;try{const data=await request('/api/workflow-dashboard');const exceptions=data.exceptions||[];$('workflowTotal').textContent=Number(data.summary?.total_practices||0);$('workflowReady').textContent=Number(data.summary?.ready_practices||0);$('workflowExceptions').textContent=exceptions.length;$('workflowMessages').textContent=Number(data.messages?.pending||0)+Number(data.messages?.failed||0);setupBanner(data.automation||{});renderExceptions(exceptions);renderUpcoming(data.upcoming||[]);}catch(error){$('workflowExceptionList').innerHTML=`<div class="workflow-empty">${error.message}</div>`;}}
  $('runWorkflowBtn')?.addEventListener('click',async()=>{const button=$('runWorkflowBtn');button.disabled=true;button.textContent='Controllo…';try{await request('/api/workflow/run',{method:'POST',body:'{}'});await load();alert('Controllo completato.');}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent='Esegui controllo';}});
  window.WTEWorkflow={load};window.addEventListener('wte:auth-login',()=>setTimeout(load,500));setInterval(load,60000);setTimeout(load,800);
})();